### ISSUE TITLE
ImportError occured if install by "pip install", and setup by git work well

### ISSUE THREAD

**Issue by Alexander-flyer** [r9y9/nnmnkwii#64] opened 2018-01-08 09:49 UTC
env: Python 3.5
First,  I install nnmnkwii by "pip install nnmnkwii" and succeed.
but when I import nnmnkwii , error occured that:

> from nnmnkwii.preprocessing.alignment import DTWAligner
> File "/export/soft/env_pytorch/img/lib/python3.5/site-packages/nnmnkwii/preprocessing/alignment.py", line 4, in <module>
>    from nnmnkwii.baseline.gmm import MLPG
>  File "/export/soft/env_pytorch/img/lib/python3.5/site-packages/nnmnkwii/baseline/gmm.py", line 5, in <module>
>    from nnmnkwii.paramgen import mlpg
>  File "/export/soft/env_pytorch/img/lib/python3.5/site-packages/nnmnkwii/paramgen/__init__.py", line 3, in <module>
>    from ._mlpg import build_win_mats, mlpg, mlpg_grad, unit_variance_mlpg_matrix
>  File "/export/soft/env_pytorch/img/lib/python3.5/site-packages/nnmnkwii/paramgen/_mlpg.py", line 9, in <module>
>    from nnmnkwii.util.linalg import cholesky_inv_banded
>  File "/export/soft/env_pytorch/img/lib/python3.5/site-packages/nnmnkwii/util/linalg.py", line 4, in <module>
>    from ._linalg import dpotri_full_L, dpotri_full_U
>ImportError: No module named 'nnmnkwii.util._linalg' 

but after downloading .zip file and setup by "python setup.py develop" ,It works well.
I feel confused.

**Comment by r9y9** [comment] 2018-01-08 10:54
Looks like cython module was not compiled successfully. I tried with a fresh python3.5 env but cannot reproduce. Could you try installing with the following command?

```
pip -v --no-cache-dir install nnmnkwii
```

This should give us more information.

**Comment by Alexander-flyer** [comment] 2018-01-08 13:39
hmm  I have uninstalled it and reinstalled it follow your suggestion,  it works well.
As a test, I uninstalled it again and install by "pip install nnmnkwii" it also works well ..
Maybe It just a problem caused by my environment at that time.
Thanks for your response, If I get any point I will feedback to you immediately.
=w=

**Comment by r9y9** [comment] 2018-06-06 15:08
I'm closing the issue. Feel free to reopen if you still see the issue.

**Closed by r9y9** 2018-06-06 15:08 UTC
